export const DEFAULT_TELEMETRY_LIMIT = 100;
export const MAX_TELEMETRY_LIMIT = 250;
export const MAX_LEDGER_READ_BYTES = 1024 * 1024;
export const MAX_NATIVE_RESPONSE_BYTES = 16 * 1024;
export const MAX_ALERT_FIELD_LENGTH = 2048;
export const MAX_ALERT_CATEGORY_LENGTH = 128;
export const MOCK_SCENARIO_DURATION_MS = 15_000;
export const MAX_CLIENT_RETAINED_ALERTS = 500;
